spring.application.name=ticket_flatform_spring

# ==================================
# DATA SOURCE (PostgreSQL)
# ==================================

spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_flatform_db
spring.datasource.username=kunhyung
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# JPA (Hibernate)
# ==================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================
# LOGGING
# ==================================
logging.level.org.hibernate.orm.jdbc.bind=TRACE